Web/MyCars.Web/Areas/Administration/Controllers/BrandsController.cs
namespace MyCars.Web.Areas.Administration.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.EntityFrameworkCore;
    using MyCars.Data;
    using MyCars.Data.Common.Repositories;
    using MyCars.Data.Models;

    public class BrandsController : AdministrationController
    {
        private readonly IDeletableEntityRepository<Brand> dataRepository;

        public BrandsController(IDeletableEntityRepository<Brand> dataRepository)
        {
            this.dataRepository = dataRepository;
        }

        // GET: Administration/Brands
        public async Task<IActionResult> Index()
        {
            return this.View(await this.dataRepository.AllWithDeleted().ToListAsync());
        }

        // GET: Administration/Brands/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var brand = await this.dataRepository.All()
                .FirstOrDefaultAsync(m => m.Id == id);
            if (brand == null)
            {
                return this.NotFound();
            }

            return this.View(brand);
        }

        // GET: Administration/Brands/Create
        public IActionResult Create()
        {
            return this.View();
        }

        // POST: Administration/Brands/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,IsDeleted,DeletedOn,Id,CreatedOn,ModifiedOn")] Brand brand)
        {
            if (this.ModelState.IsValid)
            {
                await this.dataRepository.AddAsync(brand);
                await this.dataRepository.SaveChangesAsync();
                return this.RedirectToAction(nameof(this.Index));
            }

            return this.View(brand);
        }

        // GET: Administration/Brands/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var brand = this.dataRepository.All().FirstOrDefault(x => x.Id == id);
            if (brand == null)
            {
                return this.NotFound();
            }

            return this.View(brand);
        }

        // POST: Administration/Brands/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Name,IsDeleted,DeletedOn,Id,CreatedOn,ModifiedOn")] Brand brand)
        {
            if (id != brand.Id)
            {
                return this.NotFound();
            }

            if (this.ModelState.IsValid)
            {
                try
                {
                    this.dataRepository.Update(brand);
                    await this.dataRepository.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!this.BrandExists(brand.Id))
                    {
                        return this.NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return this.RedirectToAction(nameof(this.Index));
            }

            return this.View(brand);
        }

        // GET: Administration/Brands/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var brand = await this.dataRepository.All()
                .FirstOrDefaultAsync(m => m.Id == id);
            if (brand == null)
            {
                return this.NotFound();
            }

            return this.View(brand);
        }

        // POST: Administration/Brands/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var brand = this.dataRepository.All().FirstOrDefault(x => x.Id == id);
            this.dataRepository.Delete(brand);
            await this.dataRepository.SaveChangesAsync();
            return this.RedirectToAction(nameof(this.Index));
        }

        private bool BrandExists(int id)
        {
            return this.dataRepository.All().Any(e => e.Id == id);
        }
    }
}

Web/MyCars.Web/Controllers/AdCarsController.cs
namespace MyCars.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Security.Claims;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using MyCars.Common;
    using MyCars.Data.Models;
    using MyCars.Services.Data;
    using MyCars.Web.ViewModels.AdCars;

    public class AdCarsController : Controller
    {
        private readonly IBrandsService brandsService;
        private readonly IBodyTypesService bodyTypesService;
        private readonly IFuelsService fuelsService;
        private readonly ITransmissionsService transmissionsService;
        private readonly IAdCarsService adcarsService;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IWebHostEnvironment environment;

        public AdCarsController(
            IBrandsService brandsService,
            IBodyTypesService bodyTypesService,
            IFuelsService fuelsService,
            ITransmissionsService transmissionsService,
            IAdCarsService adcarsService,
            UserManager<ApplicationUser> userManager,
            IWebHostEnvironment environment)
        {
            this.brandsService = brandsService;
            this.bodyTypesService = bodyTypesService;
            this.fuelsService = fuelsService;
            this.transmissionsService = transmissionsService;
            this.adcarsService = adcarsService;
            this.userManager = userManager;
            this.environment = environment;
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        public IActionResult Edit(int id)
        {
            var inputModel = this.adcarsService.GetById<EditAdCarInputModel>(id);
            inputModel.BrandsItems = this.brandsService.GetAllAsKeyValuePairs();
            inputModel.BodyTypeItems = this.bodyTypesService.GetAllAsKeyValuePairs();
            inputModel.FuelItems = this.fuelsService.GetAllAsKeyValuePairs();
            inputModel.TransmissionItems = this.transmissionsService.GetAllAsKeyValuePairs();

            return this.View(inputModel);
        }

        [HttpPost]
        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        public async Task<IActionResult> Edit(int id, EditAdCarInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                input.BrandsItems = this.brandsService.GetAllAsKeyValuePairs();
                input.BodyTypeItems = this.bodyTypesService.GetAllAsKeyValuePairs();
                input.FuelItems = this.fuelsService.GetAllAsKeyValuePairs();
                input.TransmissionItems = this.transmissionsService.GetAllAsKeyValuePairs();

                return this.View(input);
            }

            await this.adcarsService.UpdateAsync(id, input);

            return this.RedirectToAction(nameof(this.ById), new { id });
        }

        [Authorize]
        public IActionResult Create()
        {
            var viewModel = new CreateAdCarInputModel();
            viewModel.BrandsItems = this.brandsService.GetAllAsKeyValuePairs();
            viewModel.BodyTypeItems = this.bodyTypesService.GetAllAsKeyValuePairs();
            viewModel.FuelItems = this.fuelsService.GetAllAsKeyValuePairs();
            viewModel.TransmissionItems = this.transmissionsService.GetAllAsKeyValuePairs();

            return this.View(viewModel);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(CreateAdCarInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                input.BrandsItems = this.brandsService.GetAllAsKeyValuePairs();
                input.BodyTypeItems = this.bodyTypesService.GetAllAsKeyValuePairs();
                input.FuelItems = this.fuelsService.GetAllAsKeyValuePairs();
                input.TransmissionItems = this.transmissionsService.GetAllAsKeyValuePairs();

                return this.View(input);
            }

            // var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var user = await this.userManager.GetUserAsync(this.User);
            try
            {
                await this.adcarsService.CreateAsync(input, user.Id, $"{this.environment.WebRootPath}/images");
            }
            catch (Exception ex)
            {
                this.ModelState.AddModelError(string.Empty, ex.Message);
                input.BrandsItems = this.brandsService.GetAllAsKeyValuePairs();
                input.BodyTypeItems = this.bodyTypesService.GetAllAsKeyValuePairs();
                input.FuelItems = this.fuelsService.GetAllAsKeyValuePairs();
                input.TransmissionItems = this.transmissionsService.GetAllAsKeyValuePairs();

                return this.View(input);
            }

            return this.Redirect("/");
        }

        public IActionResult All(int id = 1)
        {
            if (id <= 0)
            {
                return this.NotFound();
            }

            const int ItemsPerPage = 12;

            var vieModel = new AdCarsListViewModel
            {
                ItemsPerPage = ItemsPerPage,
                PageNumber = id,
                AdCarsCount = this.adcarsService.GetCount(),
                AdCars = this.adcarsService.GetAll<AdCarInLIstViewModel>(id, ItemsPerPage),
            };
            return this.View(vieModel);
        }

        public IActionResult ById(int id)
        {
            var adcar = this.adcarsService.GetById<SingleAdCarViewModel>(id);

            return this.View(adcar);
        }

        [HttpPost]
        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        public async Task<IActionResult> Delete(int id)
        {
            await this.adcarsService.DeleteAsync(id);

            return this.RedirectToAction(nameof(this.All));
        }
    }
}

Web/MyCars.Web/Controllers/SearchAdCarsController.cs
namespace MyCars.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;
    using MyCars.Services.Data;
    using MyCars.Web.ViewModels.AdCars;
    using MyCars.Web.ViewModels.SearchAdCars;

    public class SearchAdCarsController : BaseController
    {
        private readonly IAdCarsService adcarsService;
        private readonly IFeaturesService featuresService;

        public SearchAdCarsController(
            IAdCarsService adcarsService,
            IFeaturesService featuresService)
        {
            this.adcarsService = adcarsService;
            this.featuresService = featuresService;
        }

        public IActionResult Index()
        {
            var viewModel = new SearchIndexViewModel
            {
                Features = this.featuresService.GetAll<FeatureNameIdViewModel>(),
            };

            return this.View(viewModel);
        }

        [HttpGet]
        public IActionResult List(SearchListInputModel input)
        {
            var viewModel = new ListViewMoel
            {
                AdCars = this.adcarsService
                .GetByFeatures<AdCarInLIstViewModel>(input.Features),
            };

            return this.View(viewModel);
        }
    }
}

Web/MyCars.Web/Views/Shared/_Layout.cshtml
@using MyCars.Common
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@this.ViewData["Title"] - @GlobalConstants.SystemName</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />    

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@GlobalConstants.SystemName</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AdCars" asp-action="All">AdCars All</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SearchAdCars" asp-action="Index">Search</a>
                        </li>
                        @if (this.User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="AdCars" asp-action="Create">Create-AdCar</a>
                            </li>
                        }
                        @if (this.User.IsInRole(GlobalConstants.AdministratorRoleName))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Administration" asp-controller="Brands" asp-action="Index">Branbs-Admin</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @this.RenderBody()
        </main>
    </div>
    
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - @GlobalConstants.SystemName - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
    @await this.RenderSectionAsync("Scripts", required: false)
</body>
</html>

Web/MyCars.Web/Views/Shared/_PagingPartial.cshtml
@model MyCars.Web.ViewModels.PagingViewModel
<nav aria-label="...">
    <ul class="pagination justify-content-center">
        <li class="page-item @if (!Model.HasPreviousPage) { <text>disabled</text> }">
            <a class="page-link" asp-action="All" asp-route-id="@Model.PreviousPageNumber">Previous</a>
        </li>
        @for (int i = Model.PageNumber - 4; i < Model.PageNumber; i++)
        {
            if (i > 0)
            {
                <li class="page-item"><a class="page-link" asp-action="All" asp-route-id="@i">@i</a></li>
            }
        }
        <li class="page-item active" aria-current="page">
            <span class="page-link">
                @Model.PageNumber
                <span class="sr-only">(current)</span>
            </span>
        </li>
        @for (int i = Model.PageNumber + 1; i <= Model.PageNumber + 4; i++)
        {
            if (i <= Model.PagesCount)
            {
                <li class="page-item"><a class="page-link" asp-action="All" asp-route-id="@i">@i</a></li>
            }
        }
        <li class="page-item @if (!Model.HasNextPage) { <text>disabled</text> }">
            <a class="page-link" asp-action="All" asp-route-id="@Model.NextPageNumber">Next</a>
        </li>
    </ul>
</nav>